### ISSUE TITLE
Feature Request: drop or select columns

### ISSUE THREAD

**Issue by MichaelChirico** [hadley/readxl#133] opened 2015-10-09 22:50 UTC
Fairly straightforward, would be nice to have functionality to in/exclude columns, especially for a case when we only need a few columns from a huge (many-columns) spreadsheet.

Most other readers have this functionality; it appears [`xlsx`]() does so by [reading in rectangular blocks of columns](https://github.com/cran/xlsx/blob/master/R/readColumns.R) and [then `cbind`ing them](https://github.com/cran/xlsx/blob/master/R/read.xlsx2.R). Not sure how much of a paradigm shift that would entail / associated slowdown.

**Comment by jennybc** [comment] 2015-10-12 04:38
Duplicate of #8

**Closed** 2015-10-12 12:58 UTC
