### ISSUE TITLE
read_excel should support vector `na` argument

### ISSUE THREAD

**Issue by LiNk-NY** [hadley/readxl#214] opened 2016-11-04 22:52 UTC
Some excel files contain multiple NA strings. Would it be better to allow multiple NA values from data? 
Such as: 
`na = c("Not Available", "Not Applicable")`

Thoughts? 
@hadley @jennybc

**Comment by jennybc** [comment] 2016-11-04 23:37
Functions like `readr::read_csv()` support vector input for `na.strings`, so this certainly seems like a nice move in the name of consistency. And it would just be useful.

Duplicate of #197, #13. Two existing PRs #56, #136. Related to #173.

**Closed** 2017-01-03 20:08 UTC
