### ISSUE TITLE
When Excel sheet tab names are numbers, read_excel finds those instead of using sheet as position

### ISSUE THREAD

**Issue by ahcyip** [hadley/readxl#168] opened 2016-05-01 18:55 UTC
read_excel appears to be defaulting to looking for the sheet name but this causes a problem when sheet names are numbers themselves and I am actually asking Excel to use Sheet= as the position.

**Comment by jennybc** [comment] 2016-05-21 16:52
Probably related to #80 and #104

**Comment by jennybc** [comment] 2017-01-24 18:24
Until proven otherwise, I regard this as a duplicate of #104.

**Closed by jennybc** 2017-01-24 18:24 UTC
Labels: reprex, sheet_rels
