### ISSUE TITLE
Read blank excel sheets with headers

### ISSUE THREAD

**Issue by zx8754** [hadley/readxl#144] opened 2015-11-03 12:17 UTC
I need to read the sheet with headers, even if there is no data.

Example: if we have an excel file _temp.xlsx_ with a sheet named _Sheet1_ with 3 columns as below with no data rows, just a header:

![image](https://cloud.githubusercontent.com/assets/5212915/10907608/66bb4890-8223-11e5-96a3-35f30ea541a5.png)

``` R
read_excel("temp.xlsx","Sheet1")
```

Gives error:

> Error: Skipped over all data

I could set `col_names = FALSE`, then use the 1st row to be a header. As I need to read multiple sheets, some will have data and some will be blank with just a header, this is a bit painful.

Any better solution?

``` R
sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readxl_0.1.0 dplyr_0.4.3 

loaded via a namespace (and not attached):
[1] magrittr_1.5   R6_2.1.1       assertthat_0.1 parallel_3.2.2 DBI_0.3.1      tools_3.2.2    Rcpp_0.12.1 
```

**Comment by jennybc** [comment] 2017-01-04 01:18
Semi-duplicate of #222. Only difference: this issue confirms same behaviour happens when column headers are present, but there's no data. I verified that.

**Closed by jennybc** 2017-01-04 01:18 UTC
