### ISSUE TITLE
Problems guessing column type data begin with large blank.

### ISSUE THREAD

**Issue by pbdanny** [hadley/readxl#172] opened 2016-05-07 07:26 UTC
One of my column started with blank for quite large (about 8000 rows), then follow with the text data.
When importing, there are warning that this column was determined to be integer and then importing fails, resulted in all NA for this column.

My only work-aroud is to specify all the col_type.

**Comment by tklebel** [comment] 2016-05-07 10:54
Duplicate of #131 

Temporary solution: 
```R
# install.packages("devtools")
devtools::install_github("tklebel/readxl")
read_excel("file.xlsx", n = 10000)
```

**Comment by pbdanny** [comment] 2016-05-08 03:40
Sorry for the duplicated issue.
Thx for you promptly reply.

**Closed** 2017-01-03 23:28 UTC
