### ISSUE TITLE
readxl and shiny do not work together

### ISSUE THREAD

**Issue by ingvarp** [hadley/readxl#109] opened 2015-06-06 00:00 UTC
Shiny function  fileInput stores uploaded files in a temp directory without extension. When I try to read the uploaded file with readxl it gives me the error: "Error: Unknown format ."
The same error I am getting when I rename an .xls file removing its extension and trying to read it. 

The workaround is to rename the uploaded file adding the .xls extension back.
file.rename(inFile$datapath, paste(inFile$datapath, ".xlsx", sep=""))

On the topic of detection excel files without extension there is a thread on a mathlab forum that has few working solutions.

http://www.mathworks.com/matlabcentral/answers/76710-detecting-excel-files-without-excel-extension

**Comment by reidjax** [comment] 2015-07-09 21:09
+1

**Comment by adilapapaya** [comment] 2015-07-10 22:16
+1

**Comment by hadley** [comment] 2015-07-30 22:31
Duplicate of #85

**Closed by hadley** 2015-07-30 22:31 UTC
