### ISSUE TITLE
Feature request: allow multiple values for na

### ISSUE THREAD

**Issue by sachsmc** [hadley/readxl#13] opened 2015-03-19 13:28 UTC
E.g. `na = c("NA", "N/A")`

**Comment by jakesherman** [comment] 2015-04-09 14:52
Seconded.

**Comment by sunitj** [comment] 2015-04-09 16:13
:+1: Came here to make the same request. Glad I'm not the only one.

**Comment by mattsigal** [comment] 2015-05-14 13:13
I would also love to see this implemented!

**Comment by jennybc** [comment] 2015-05-23 22:38
:+1:

**Comment by MichaelChirico** [comment] 2015-10-11 00:06
Also would like this. Can't imagine it's too hard to implement either... any particular hold-up?

**Comment by MichaelChirico** [comment] 2015-10-11 02:41
Seems like the crux of the issue is in the [XlsxCell class/methods definition](https://github.com/hadley/readxl/blob/master/src/XlsxCell.h), where an `NA` is produced with the condition (in the [type](https://github.com/hadley/readxl/blob/master/src/XlsxCell.h#L149), [asDate](https://github.com/hadley/readxl/blob/master/src/XlsxCell.h#L78), [asDouble](https://github.com/hadley/readxl/blob/master/src/XlsxCell.h#L70), and [asCharSxp](https://github.com/hadley/readxl/blob/master/src/XlsxCell.h#L92) methods):

    if (v == NULL || na.compare(v->value()) == 0)

Anyone more facile with `C` know how to extend that to non-scalar `na`? Is there nothing like `any(na.compare(v->value()) == 0)`?

**Comment by MichaelChirico** [comment] 2015-10-12 18:43
I think I've made some progress on implementing this, but am sort of in the deep end with my limited C++ knowhow.

Check out my working branch [here](https://github.com/MichaelChirico/readxl/tree/multiple_na);

currently I'm getting the error from XlsxCell.h on lines 92 & 109: 

>XlsxCell.h: In lambda function:
XlsxCell.h:92:112: error: ‘v’ was not declared in this scope
       if (!parseString(is, &value) || std::any_of(na.cbegin(), na.cend(), [&](std::string i){ return i.compare(v->value()) == 0; })) {

Anyone have suggestions for how to fix this?

**Comment by MichaelChirico** [comment] 2015-10-12 20:20
The version I've got on my branch is now functional (see [Pull Request](https://github.com/hadley/readxl/pull/136)).

If you're impatient you can use the version on [my branch](https://github.com/MichaelChirico/readxl/tree/multiple_na) (via `install_github("MichaelChirico/readxl@multiple_na")`). I'm not sure the procedure for documentation / tests around here, so it may need a bit of polishing before it's officially merged.

**Comment by yimingli** [comment] 2016-02-16 15:35
+1

**Closed** 2017-01-19 18:29 UTC
Labels: feature
