### ISSUE TITLE
[feature request] read in region of sheet

### ISSUE THREAD

**Issue by wdkrnls** [hadley/readxl#30] opened 2015-03-22 01:45 UTC
A key feature of `XLConnect` in my work is being able to read in an arbitrary region of cells from a worksheet using `startRow`, `startCol`, `endRow`, and `endCol` arguments in the `readWorksheet` function. This functionality is very handy for me as I often receive Excel files which contain many smaller tables on a single sheet. Would an equivalent feature be in scope for this project? I'd love to ditch `rJava` if I could.

**Comment by williamscott** [comment] 2015-03-22 05:40
In a similar spirit, having an option to designate the area to be read-in via an Excel named range would also be handy ... this would mean that the data to be imported could be precisely identified without being on a separate sheet.

**Comment by jennybc** [comment] 2015-03-22 19:30
Almost a duplicate of #8

**Closed** 2015-03-23 11:04 UTC
