### ISSUE TITLE
read_excel appends empty rows when first rows are empty

### ISSUE THREAD

**Issue by stla** [hadley/readxl#237] opened 2017-01-26 11:47 UTC
Hello,
I have this Excel sheet:
![capture](https://cloud.githubusercontent.com/assets/4466543/22330170/28fece82-e3c5-11e6-94e5-263c89391d72.PNG)
The first row is empty, and row 5 is empty as well (no value, no format).

And I get that, as if `read_excel` imported row 5:
```
> dd <- read_excel("./inst/extdata/xlsx/temp.xlsx", sheet=1)
> dd
   A  B
1  1  3
2  2  4
3 NA NA 
```

**Comment by jennybc** [comment] 2017-01-26 17:50
Duplicate of #224

**Closed by jennybc** 2017-01-26 17:50 UTC
