### ISSUE TITLE
Error when installing the package.

### ISSUE THREAD

**Issue by JT85** [hadley/readxl#87] opened 2015-04-21 07:30 UTC
The error:

    * installing *source* package ‘readxl’ ...
    ** package ‘readxl’ successfully unpacked and MD5 sums checked
    ** libs
    g++ -m64 -I/usr/include/R -DNDEBUG -Iunix -I. -I/usr/local/include -I"/home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include"  -std=c++0x -fpic  -O2 -g  -c RcppExports.cpp -o RcppExports.o
    g++ -m64 -I/usr/include/R -DNDEBUG -Iunix -I. -I/usr/local/include -I"/home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include"  -std=c++0x -fpic  -O2 -g  -c XlsWorkBook.cpp -o XlsWorkBook.o
    In file included from /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/RcppCommon.h:74,
                 from /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp.h:27,
                 from XlsWorkBook.cpp:1:
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h: In constructor ‘tinyformat::detail::FormatListN<N>::FormatListN(const Args& ...) [with Args = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int N = 2]’:
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:902:   instantiated from ‘tinyformat::detail::FormatListN<sizeof (Args ...)> tinyformat::makeFormatList(const Args& ...) [with Args = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int]’
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:938:   instantiated from ‘void tinyformat::format(std::ostream&, const char*, const Args& ...) [with Args = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int]’
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:947:   instantiated from ‘std::string tinyformat::format(const char*, const Args& ...) [with Args = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int]’
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/exceptions.h:207:   instantiated from ‘void Rcpp::warning(const char*, const T1&, const T2&) [with T1 = std::string, T2 = int]’
    CellType.h:32:   instantiated from here
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:853: error: bad array initializer
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h: In constructor ‘tinyformat::detail::FormatListN<N>::FormatListN(const Args& ...) [with Args = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int N = 1]’:
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:902:   instantiated from ‘tinyformat::detail::FormatListN<sizeof (Args ...)> tinyformat::makeFormatList(const Args& ...) [with Args = std::basic_string<char, std::char_traits<char>, std::allocator<char> >]’
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:938:   instantiated from ‘void tinyformat::format(std::ostream&, const char*, const Args& ...) [with Args = std::basic_string<char, std::char_traits<char>, std::allocator<char> >]’
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:947:   instantiated from ‘std::string tinyformat::format(const char*, const Args& ...) [with Args = std::basic_string<char, std::char_traits<char>, std::allocator<char> >]’
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/exceptions.h:256:   instantiated from ‘void Rcpp::stop(const char*, const T1&) [with T1 = std::basic_string<char, std::char_traits<char>, std::allocator<char> >]’
    XlsWorkBook.h:28:   instantiated from here
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:853: error: bad array initializer
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h: In constructor ‘tinyformat::detail::FormatListN<N>::FormatListN(const Args& ...) [with Args = int, int, char*, int N = 3]’:
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:902:   instantiated from ‘tinyformat::detail::FormatListN<sizeof (Args ...)> tinyformat::makeFormatList(const Args& ...) [with Args = int, int, char*]’
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:938:   instantiated from ‘void tinyformat::format(std::ostream&, const char*, const Args& ...) [with Args = int, int, char*]’
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:947:   instantiated from ‘std::string tinyformat::format(const char*, const Args& ...) [with Args = int, int, char*]’
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/exceptions.h:212:   instantiated from ‘void Rcpp::warning(const char*, const T1&, const T2&, const T3&) [with T1 = int, T2 = int, T3 = char*]’
    XlsWorkSheet.h:128:   instantiated from here
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:853: error: bad array initializer
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h: In constructor ‘tinyformat::detail::FormatListN<N>::FormatListN(const Args& ...) [with Args = int, int, double, int N = 3]’:
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:902:   instantiated from ‘tinyformat::detail::FormatListN<sizeof (Args ...)> tinyformat::makeFormatList(const Args& ...) [with Args = int, int, double]’
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:938:   instantiated from ‘void tinyformat::format(std::ostream&, const char*, const Args& ...) [with Args = int, int, double]’
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:947:   instantiated from ‘std::string tinyformat::format(const char*, const Args& ...) [with Args = int, int, double]’
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/exceptions.h:212:   instantiated from ‘void Rcpp::warning(const char*, const T1&, const T2&, const T3&) [with T1 = int, T2 = int, T3 = double]’
    XlsWorkSheet.h:139:   instantiated from here
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:853: error: bad array initializer
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h: In constructor ‘tinyformat::detail::FormatListN<N>::FormatListN(const Args& ...) [with Args = int, int, xls::BYTE*, int N = 3]’:
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:902:   instantiated from ‘tinyformat::detail::FormatListN<sizeof (Args ...)> tinyformat::makeFormatList(const Args& ...) [with Args = int, int, xls::BYTE*]’
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:938:   instantiated from ‘void tinyformat::format(std::ostream&, const char*, const Args& ...) [with Args = int, int, xls::BYTE*]’
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:947:   instantiated from ‘std::string tinyformat::format(const char*, const Args& ...) [with Args = int, int, xls::BYTE*]’
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/exceptions.h:212:   instantiated from ‘void Rcpp::warning(const char*, const T1&, const T2&, const T3&) [with T1 = int, T2 = int, T3 = xls::BYTE*]’
    XlsWorkSheet.h:147:   instantiated from here
    /home/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/utils/tinyformat.h:853: error: bad array initializer
    make: *** [XlsWorkBook.o] Error 1
    ERROR: compilation failed for package ‘readxl’
    * removing ‘/home/R/x86_64-unknown-linux-gnu-library/3.1/readxl’

Session info:

    R version 3.1.0 (2014-04-10)
    Platform: x86_64-unknown-linux-gnu (64-bit)
    
    locale:
     [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
     [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] Rcpp_0.11.5
    
    loaded via a namespace (and not attached):
    [1] tools_3.1.0

**Comment by hadley** [comment] 2015-04-21 12:20
Duplicate of #78

**Closed by hadley** 2015-04-21 12:20 UTC
