### ISSUE TITLE
Feature request: add more "na.strings" 

### ISSUE THREAD

**Issue by martinbel** [hadley/readxl#96] opened 2015-05-07 18:13 UTC
Most read functions in base R allow you to pass more than one na.string in order to identify people diverse ways to encode missing values, such as: ?, ., null, etc. 
So far it's posible to read the blancks and one more. I found this is ok, most of the times but It would be great to add the posibility to add more options, right?

BTW, nice work with the package!

**Comment by jennybc** [comment] 2015-05-07 18:31
Duplicate of #13

**Closed** 2015-05-07 18:47 UTC
