### ISSUE TITLE
DEFINEDNAME

### ISSUE THREAD

**Issue by BrettRey** [hadley/readxl#111] opened 2015-06-16 11:40 UTC
> mydata <- read_excel("~/Documents/Rdata/DetPronFeatures.xls") %>% data.frame()
DEFINEDNAME: 01 00 00 30 0b 00 00 00 02 00 00 00 00 00 00 5a 5f 45 41 46 43 38 42 30 46 5f 39 37 38 46 5f 31 34 34 43 5f 39 37 32 31 5f 42 31 42 32 36 37 36 30 36 32 34 46 5f 2e 77 76 75 2e 43 6f 6c 73 3b 00 00 00 00 ff ff 17 00 20 00 
DEFINEDNAME: 01 00 00 30 0b 00 00 00 02 00 00 00 00 00 00 5a 5f 45 41 46 43 38 42 30 46 5f 39 37 38 46 5f 31 34 34 43 5f 39 37 32 31 5f 42 31 42 32 36 37 36 30 36 32 34 46 5f 2e 77 76 75 2e 43 6f 6c 73 3b 00 00 00 00 ff ff 17 00 20 00 
DEFINEDNAME: 01 00 00 30 0b 00 00 00 02 00 00 00 00 00 00 5a 5f 45 41 46 43 38 42 30 46 5f 39 37 38 46 5f 31 34 34 43 5f 39 37 32 31 5f 42 31 42 32 36 37 36 30 36 32 34 46 5f 2e 77 76 75 2e 43 6f 6c 73 3b 00 00 00 00 ff ff 17 00 20 00 
DEFINEDNAME: 01 00 00 30 0b 00 00 00 02 00 00 00 00 00 00 5a 5f 45 41 46 43 38 42 30 46 5f 39 37 38 46 5f 31 34 34 43 5f 39 37 32 31 5f 42 31 42 32 36 37 36 30 36 32 34 46 5f 2e 77 76 75 2e 43 6f 6c 73 3b 00 00 00 00 ff ff 17 00 20 00

**Comment by hadley** [comment] 2015-06-16 12:23
Duplicate of #82

**Closed by hadley** 2015-06-16 12:23 UTC

**Comment by Dripdrop12** [comment] 2015-12-14 16:02
Am I the only person who still gets the DEFINEDNAME printout?  I tried installing the GitHub version, but the problem persists.

Here's my session info:

sessionInfo(package = 'readxl')
R version 3.2.1 (2015-06-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
character(0)

other attached packages:
[1] readxl_0.1.0.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.2     lubridate_1.3.3 grDevices_3.2.1 xlsxjars_0.6.1  digest_0.6.8   
 [6] dplyr_0.4.3     assertthat_0.1  R6_2.1.1        plyr_1.8.3      DBI_0.3.1      
[11] magrittr_1.5    datasets_3.2.1  httr_1.0.0      xlsx_0.5.7      stringi_1.0-1  
[16] utils_3.2.1     curl_0.9.3      reshape2_1.4.1  graphics_3.2.1  devtools_1.9.1 
[21] base_3.2.1      tools_3.2.1     stringr_1.0.0   parallel_3.2.1  stats_3.2.1    
[26] rJava_0.9-7     memoise_0.2.1   methods_3.2.1

**Comment by sheriferson** [comment] 2015-12-23 00:55
@Dripdrop12 See my workaround posted as a comment on #82 [here](https://github.com/hadley/readxl/issues/82#issuecomment-166767220). It might help you in your usage.
